### ISSUE TITLE
Teemo.NEO.send() returning error

### ISSUE THREAD

**Issue by vincentgeneste** [NewEconoLab/TeemoWallet#1]
Hello!

Trying to implement Teemo dAPI and I'm having issue with the send() function.
I tried with your own example, I do have enough GAS in my wallet, but for some reason it's not working.

I get the popup once I do a send(), but there's an error in the console and the popup looks empty.

<img width="421" alt="Screen Shot 2019-03-19 at 20 31 40" src="https://user-images.githubusercontent.com/25534589/54657265-04e99200-4a86-11e9-8ed8-cd3dfaa97409.png">

<img width="1535" alt="Screen Shot 2019-03-19 at 20 29 30" src="https://user-images.githubusercontent.com/25534589/54657244-ef746800-4a85-11e9-8b95-466a9b0ae90f.png">

**Comment by QingmingZi** [comment]
@vincentgeneste Thank you very much for your feedback. This method is one of the few that we haven't fully completed yet. Expected to be completed tomorrow

**Comment by QingmingZi** [comment]
@vincentgeneste send() is OK, Now

**Comment by vincentgeneste** [comment]
I do get the popup now, but I still get an error when trying to send something, and it's not very descriptive why it failed?

<img width="424" alt="Screen Shot 2019-03-20 at 10 42 52" src="https://user-images.githubusercontent.com/25534589/54706805-01ddb880-4afd-11e9-9d79-e74a39a6f682.png">

**Comment by QingmingZi** [comment]
@vincentgeneste Recommended to get the latest code test (testnet)
![image](https://user-images.githubusercontent.com/12634683/54903887-ea953580-4f17-11e9-8e41-9d675bc75d6b.png)

**Comment by vincentgeneste** [comment]
Is it only working on testnet for now? Will give it a try tonight

**Comment by vincentgeneste** [comment]
Ok just tested and it works when using

"asset": "602c79718b16e442de58778e148d0b1084e3b2dffd5de6b7b16cee7969282de7"

But when I use "asset":"GAS" like in your documentation, it does not.

**Comment by QingmingZi** [comment]
Sorry, this is a problem with the documentation. The asset ID should always be used instead of the asset name or asset unit. Because we believe that the asset name or asset unit is not unique and is not suitable as an argument to the asset field. https://dapi.nel.group/en/#send has been fixed

**Comment by vincentgeneste** [comment]
Ok got it if you updated the documentation that’s fine :-)
