### ISSUE TITLE
Teemo.NEO.getBalance() not returning NEP-5

### ISSUE THREAD

**Issue by vincentgeneste** [NewEconoLab/TeemoWallet#3]
getBalance() works correctly both on TestNet and MainNet, but currently does not return the NEP-5 assets.

**Comment by vincentOpenSource** [comment]
Can you tell me the asset you're looking for, id?

**Comment by vincentOpenSource** [comment]
![ZCR%_UTT@@ V(VIHM0CU@CJ](https://user-images.githubusercontent.com/35094472/54903038-dfd9a100-4f15-11e9-9920-6ea5eecf2dbe.png)

This interface is normally available, so far we haven't found a problem in our tests

**Comment by vincentOpenSource** [comment]
Is it possible to give input parameters?

**Comment by vincentgeneste** [comment]
Based on your documentation, and based on how O3 implement it, I thought without specifying an asset it should return all balances?

Cause right now I don't specify any and it only returns NEO and GAS.

**Comment by vincentgeneste** [comment]
Teemmo.NEO.getBalance({
            "params": [
            {
              "address": "address",
              "fetchUTXO":false
            }
            ],
            "network": 'MainNet'
          })

Is returning only NEO and GAS.

**Comment by QingmingZi** [comment]
@vincentgeneste At present, we mainly meet all the APIs of the test network first, and the main network is not completely good.

**Comment by QingmingZi** [comment]
@vincentgeneste In addition, if you do not define an asset ID, we will return NEO, GAS, CGAS, and NNC assets by default, as prompted by our documentation. However, in the next big version, we will provide the asset setting function to return the balance of all the assets you need at one time. Showing all NEP5 is not recommended, NEP5 is too much

**Comment by vincentgeneste** [comment]
Okay, its just that I don't know which assets the users has in advance, so I usually prefer to query for "all" instead of looping all of them :/

**Comment by QingmingZi** [comment]
In general, Dapp will have specific asset settings, do you think so? Or do you need to make a transfer page?

**Comment by vincentgeneste** [comment]
So in my case I’m using it to list all the users assets/NEP5 that’s why I prefer to have a single call returning all balances.

I can use a third party call if you can’t provide me with this, but I think it’s definitely needed.

**Comment by QingmingZi** [comment]
https://api.nel.group/api/testnet

**Comment by vincentgeneste** [comment]
It’s ok then, I’ll use something else for the all balances call. But I’d be interested if you had that directly :-) closing the issue.
